name: Test, Build, and Push Image to Docker

on:
  push:
    branches:
      - 'master'
      - 'development'
    tags:
      - 'v*'

env:
  DOCKER_REPO_NAME: kaw393939/mywebclass

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ["lts/*"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Enable Docker BuildKit
        run: docker build --progress=plain --secret id=DOCKER_BUILDKIT_CONFIG,env=DOCKER_BUILDKIT_CONFIG=./config.json --platform=local -o type=docker,dest=./Dockerfile .
        env:
          DOCKER_BUILDKIT_CONFIG: |
            {
              "build": {
                "cache-from": ["type=registry,ref={{ .Image }}"],
                "cache-to": ["type=inline"]
              }
            }
      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: |
            ~/.cache
            ./node_modules
          key: ${{ runner.os }}-${{ env.DOCKER_REPO_NAME }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-${{ env.DOCKER_REPO_NAME }}-
            ${{ runner.os }}-
      - name: Set up Node ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: |
          npm install
          npx playwright install-deps
      - name: Test with Playwright
        id: playwright-tests
        run: |
          npm test
      - if: steps.playwright-tests.outcome == 'success'
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.DOCKER_REPO_NAME }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          driver-options: network=host
          platform: linux/amd64,linux/arm/v7,linux/arm64/v8
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm/v7,linux/arm64/v
