name: Test, Build, and Push Image to Docker

on:
  push:
    branches:
      - 'master'
      - 'development'
    tags:
      - 'v*'

env:
  DOCKER_REPO_NAME: kaw393939/mywebclass

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ "3.11" ]
        node-version: [ "18" ]

    container:
      image: node:${{ matrix.node-version }}-alpine

    services:
      redis:
        image: redis:latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Cache dependencies
        id: cache-dependencies
        uses: actions/cache@v2
        with:
          path: |
            ~/.npm
            ~/.cache
          key: ${{ runner.os }}-node-${{ matrix.node-version }}-${{ hashFiles('**/package-lock.json') }}
        run: |
          npm ci

      - name: Install dependencies
        run: |
          npm install

      - name: Test with Playwright
        id: playwright-tests
        run: |
          npm test

      - name: Build and push Docker image
        if: steps.playwright-tests.outcome == 'success'
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: 'linux/arm64/v8, linux/amd64'
          push: true
          tags: ${{ env.DOCKER_REPO_NAME }}:latest, ${{ env.DOCKER_REPO_NAME }}:${{ github.sha }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
