name: Build and Test Docker Image

on:
  push:
  pull_request:


jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set Docker buildx environment
        uses: docker/setup-buildx-action@v1

      - name: Build Docker image
        run: docker build --tag myapp .

      - name: Start Docker container
        run: docker run -d -p 8080:80 -e PW_SERVICE_BASE_URL=http://localhost:8080 myapp

      - name: Run Playwright tests
        uses: microsoft/playwright-github-action@v1
        with:
          browser: chromium
          install-browser: true
          script-path: tests
