name: Build and Test Docker Image

on:
  push:
  pull_request:

env:
  DOCKER_IMAGE: kaw393939/mywebclass

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile
          push: false
          platforms: linux/amd64
          tags: ${{ env.DOCKER_IMAGE }}:latest

      - name: Start Docker container
        run: |
          docker run -d -p 8080:80 --network host ${{ env.DOCKER_IMAGE }}:latest
          export PW_SERVICE_BASE_URL=http://localhost:8080

      - name: Install dependencies
        run: npm ci

      - name: Run Playwright tests
        uses: microsoft/playwright-github-action@v1
        with:
          browser: chromium
          install-browser: true
          script-path: path/to/playwright/tests