name: Build and Test Docker Image

on:
  push:
  pull_request:

env:
  DOCKER_IMAGE: kaw393939/mywebclass

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
   
      - name: Start Docker container
        runs:
          using: 'docker'
          image: 'Dockerfile'
        run: |
          export PW_SERVICE_BASE_URL=http://localhost:8080

      - name: Install dependencies
        run: npm ci

      - name: Run Playwright tests
        uses: microsoft/playwright-github-action@v1
        with:
          browser: chromium
          install-browser: true
          script-path: path/to/playwright/tests